apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: location-translator
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: location-translator
spec:
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  source:
    git:
      url: https://github.com/tap-scenario-apps/atm-locator-backend
      ref:
        branch: main
    subPath: location-translator